image: "gitlab.ubic.tech:4567/docker/node:12.22"

cache:
  key:
    files:
      - yarn.lock
  paths:
    - .yarn
    - node_modules/
  policy: pull

variables:
  REGISTRY_URL: "gitlab.ubic.tech:4567"
  IMAGE_NAME: $REGISTRY_URL/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME

stages:
  - build_cache
  - lint
  - build
  - dockerize

build_cache:
  stage: build_cache
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - .yarn
      - node_modules/
    policy: push
  only:
    changes:
      - yarn.lock
  script:
    - yarn install --cache-folder .yarn

lint:
  stage: lint
  except:
    - tags
  script:
    - yarn install --cache-folder .yarn
    - yarn lint

build:
  stage: build
  only:
    - tags
    - master
    - develop
  script:
    - yarn install --cache-folder .yarn
    - yarn build
  artifacts:
    expire_in: 1 day
    paths:
      - dist/*

build_storybook:
  stage: build
  only:
    - develop
  script:
    - yarn install --cache-folder .yarn
    - yarn build-storybook
  artifacts:
    expire_in: 1 day
    paths:
      - dist/*

dockerize:
  image: gitlab.ubic.tech:4567/docker/docker:stable
  cache: {}
  services:
    - name: gitlab.ubic.tech:4567/docker/dind/docker:dind
      alias: docker
  stage: dockerize
  only:
    - tags
    - master
    - develop
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY_URL
    - docker build --pull --cache-from $IMAGE_NAME -t $IMAGE_NAME -f Dockerfile .
    - docker push $IMAGE_NAME
